title: Super-Resolution Color Enhancement
description: Aligning Subjective and Objective Assessments in Super-Resolution Models - SCIA 2024
theme: minima
baseurl: ""
url: "https://yourusername.github.io/super-resolution-color"
author:
  name: Your Name
  email: your.email@example.com
  url: "https://yourwebsite.com"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - _config.yml
